### PR TITLE
fix(esm): add explicit extensions to imports/exports

### LINKED ISSUE #14: Add files extensions in imports/exports to make the lib fully compatible with ESM
Hey 👋,

- `cli-testing-library` version: 1.0.2
- Testing Framework and version: vitest@0.13.0
  
- DOM Environment:
  

### Problem description:

When using ES modules, the types definitions aren't correctly generated so types are missing:

image

### Suggested solution:

For the types to be seen in a ESM environment, you need to import all the local files with their full path, including the extension of the file:
- `./foo` -> `./foo.js` (`.js` also in TypeScript, I know it's weird but I don't make the rules 😄)
- `./bar` -> `./bar/index.js`

Your code will be compatible with both CJS + ESM that way! 🥳 

For references: https://www.typescriptlang.org/docs/handbook/esm-node.html (this is no longer experimental as of TypeScript 4.7)

Especially this part:
image

### PR DESCRIPTION
**Pull request by jgoux**
I'm unable to run the tests and the build seems broken. :/

I think it's because the project is doing nonconventional things like requiring `ts` files from `js` files. 😅 

I added an ESLint rule to ensure that extensions are set in imports/exports.

Also, it seems like the `npm run format` wasn't run because it touched a bunch of files.

**What**:

Add extensions to all imports/exports to be fully compatible with ESM modules

**Why**:

Resolves #14 

**How**:

**Checklist**:

- [ ] Tests
- [ ] TypeScript definitions updated
- [ ] Ready to be merged

### CODE REVIEW

**Comment by crutchcorn** [comment]
@jgoux can you rebase from `main` if possible? (force pushing is OK

I ran `npm run format` on `main` to hopefully make the diffing easier

**Comment by jgoux** [comment]
> @jgoux can you rebase from `main` if possible? (force pushing is OK)
> 
> I ran `npm run format` on `main` to hopefully make the diffing easier

Done! Could you look into the build and tests? I think the most reasonable move would be to have everything in TS.

**Comment by crutchcorn** [comment]
> Could you look into the build and tests?

Yup yup! 

> I think the most reasonable move would be to have everything in TS.

Definitely not opposed to this, but I'm curious how ["upstream"](https://github.com/testing-library/dom-testing-library) handles this, given that this mixture of both JS and TS come from the same codebase structure as there.

**Comment by jgoux** [comment]
After playing a bit with the types generated by your package I no longer think the issue is with the explicit file extensions (even if it's a best practice 😄).

It seems that the type `RenderResult` is incorrect in the type definitions. Is it something you maintain by hand?

This line is incorrect: https://github.com/crutchcorn/cli-testing-library/blob/main/types/pure.d.ts#L4
`queries` is a value, not a type (and this value doesn't exist in `./get-queries-for-instance`.

I think doing should fix everything!
```ts
import * as queries from './queries'
import type { BoundFunction } from './get-queries-for-instance'
```

**Pull request closed without merging**
